tool_calling_atropos_resources_server:
  resources_servers:
    atropos:
      entrypoint: app.py
      domain: agent

      atropos_path: /raid/home/cmunley/Gym/atropos
      environment_module: environments.tool_use_multiturn_server
      environment_class: MultiTurnToolCallingEnv
      group_size: 8
      env_args: {}

tool_calling_atropos_agent:
  responses_api_agents:
    atropos_agent:
      entrypoint: app.py
      resources_server:
        type: resources_servers
        name: tool_calling_atropos_resources_server
